[project]
sdk_version = "0.10.0"
name = "band3"

[entrypoint]
file_path = "assets/default.xex"
out_directory_path = "generated"
includes = [
  "band3_config.toml",
  "band3_rb3dx.toml",
]

longjmp_address = 0x82BBB620
setjmp_address = 0x82BBBA50
d3d12_readback_resolve = true

